# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('auctionenddate', otree.db.models.FloatField(null=True)),
                ('work_end_date', otree.db.models.FloatField(null=True)),
                ('num_contracts_closed', otree.db.models.IntegerField(null=True)),
                ('day_over', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('last_message', otree.db.models.StringField(max_length=10000, null=True)),
                ('wage_list', otree.db.models.IntegerField(max_length=100, null=True)),
                ('contracts_dump', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='italiandirect_group', to='otree.Session')),
            ],
            options={
                'db_table': 'italiandirect_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='JobContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', otree.db.models.IntegerField(null=True)),
                ('accepted', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('amount_updated', otree.db.models.IntegerField(blank=True, null=True)),
                ('tasks_corr', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('tasks_att', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('created_at', otree.db.models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', otree.db.models.DateTimeField(auto_now=True, null=True)),
                ('auctionenddate', otree.db.models.FloatField(null=True)),
                ('day_over', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', otree.db.models.IntegerField(null=True)),
                ('created_at', otree.db.models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', otree.db.models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('treatment', otree.db.models.StringField(max_length=10000, null=True)),
                ('wage_offer', otree.db.models.IntegerField(null=True)),
                ('tax_outcome', otree.db.models.PositiveIntegerField(null=True)),
                ('last_correct_answer', otree.db.models.IntegerField(null=True)),
                ('tasks_attempted', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('tasks_correct', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('matched', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('job_to_do_updated', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('offers_dump', otree.db.models.StringField(max_length=10000, null=True)),
                ('job_contract_dump', otree.db.models.StringField(max_length=10000, null=True)),
                ('pay', otree.db.models.CurrencyField(null=True)),
                ('total_payoff', otree.db.models.CurrencyField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='italiandirect.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='italiandirect_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='italiandirect_player', to='otree.Session')),
            ],
            options={
                'db_table': 'italiandirect_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('wp_to_delete_completion', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='italiandirect_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'italiandirect_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='italiandirect.Subsession'),
        ),
        migrations.AddField(
            model_name='offer',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='italiandirect.Player'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='italiandirect.Player', unique=True),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_to_do', to='italiandirect.Player'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='italiandirect.Subsession'),
        ),
    ]
