# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endsurvey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'endsurvey_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('age', otree.db.models.PositiveIntegerField(null=True, verbose_name='Età')),
                ('sex', otree.db.models.PositiveIntegerField(choices=[[1, 'Uomo'], [2, 'Donna']], null=True, verbose_name='Sesso')),
                ('year_of_study', otree.db.models.PositiveIntegerField(null=True, verbose_name='Anno di Studio (0 se non sei uno studente, 1 se sei al primo anno di università etc)')),
                ('area_of_study', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Campo di studio (nessuno se non sei uno studente)')),
                ('nationality', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Nazionalità')),
                ('tell_earnings', otree.db.models.PositiveIntegerField(choices=[[1, 'Sì'], [2, 'No']], null=True, verbose_name='Hai intenzione di dire ad altre persone (partecipanti) quanto hai guadagnato?')),
                ('heard_before', otree.db.models.PositiveIntegerField(choices=[[1, 'Sì'], [2, 'No']], null=True, verbose_name='Eri già a conoscenza di questo esperimento prima di venire al laboratorio?')),
                ('first_experiment', otree.db.models.PositiveIntegerField(choices=[[1, 'Sì'], [2, 'No']], null=True, verbose_name='Avevi già partecipato a un esperimento in precedenza?')),
                ('similar_experiment', otree.db.models.PositiveIntegerField(choices=[[1, 'Sì'], [2, 'No']], null=True, verbose_name='Avevi già partecipato ad un esperimento simile in precedenza?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endsurvey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endsurvey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endsurvey_player', to='otree.Session')),
            ],
            options={
                'db_table': 'endsurvey_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endsurvey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'endsurvey_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endsurvey.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endsurvey.Subsession'),
        ),
    ]
